pydantic_extra_types/types/color.py

```sh
def _get_pydantic_modify_json_schema(obj: Any) -> typing.Callable[[JsonSchemaValue], None] | None:
modify_js_function = getattr(obj, '__pydantic_modify_json_schema__', None)
if modify_js_function is None and hasattr(obj, '__modify_schema__'):
>           warnings.warn(
'The __modify_schema__ method is deprecated, use __pydantic_modify_json_schema__ instead',
DeprecationWarning,
)
E           DeprecationWarning: The __modify_schema__ method is deprecated, use __pydantic_modify_json_schema__ instead
venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py:712: DeprecationWarning
```

:bug: deprecate `__modify_schema__` method

---

pydantic_extra_types/types/color.py
tests/test_types_color.py

Addresses my comment on #20.
Note that with the change from #20, if you try to generate a JSON schema for a model with a field of type Color, it actually errors:
```
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.FunctionSchema (<bound method Color._validate of <class 'pydantic_extra_types.types.color.Color'>>)
```

Fix Color JSON schema generation

---

pydantic_extra_types/color.py
tests/test_types_color.py

Implementation of #58 
---
I opted not to put it in the existing `COLORS_BY_NAME` dictionary as these are all RGB values, and this requires RGBA values. This would then require adding a fourth `None` value to all the tuples, adjusting all that logic, etc.; and that seems overkill for this single color.

Add support for transparent Color

---

pydantic_extra_types/mac_address.py
tests/test_mac_address.py

There's a MAC address validation issue here [PR](https://github.com/pydantic/pydantic-extra-types/pull/71)
This PR deletes the `__init__` function and uses the pydantic functions to return a MAC address in the correct format. 
Selected Reviewer: @Kludex

Fix mac adddress validation

---

pydantic_extra_types/color.py

Extends https://github.com/pydantic/pydantic/pull/7082 and replaces https://github.com/pydantic/pydantic/pull/7080
Selected Reviewer: @yezz123

Refactor: use stdlib and remove useless code

---

pydantic_extra_types/coordinate.py

- Closes #88
Since `Latitude` and `Longitude` are lazily evaluated, we have the issue described in the issue. 😅  
Selected Reviewer: @yezz123

Make Latitude and Longitude evaluated

---

pydantic_extra_types/color.py
tests/test_types_color.py

Fixes #66 
Selected Reviewer: @Kludex

Add long and short format to as_hex

---

pydantic_extra_types/country.py
pydantic_extra_types/payment.py
pydantic_extra_types/phone_numbers.py
pydantic_extra_types/routing_number.py

Partly addresses issue #99 
More specifically, solves this deprecation warning:
```
py3.11/lib/python3.11/site-packages/pydantic_extra_types/phone_numbers.py:33: DeprecationWarning: `general_after_validator_function` is deprecated, use `with_info_after_validator_function` instead.
return core_schema.general_after_validator_function(
```

Replaced pydantic_core deprecated method

---

Makefile

Update pip-compile call

---

pydantic_extra_types/isbn.py
tests/test_isbn.py
tests/test_json_schema.py

Implementation of [issue-115](https://github.com/pydantic/pydantic-extra-types/issues/115)
-----
The `pydantic_extra_types.isbn` module provides functionality to receive and validate ISBN 
(International Standard Book Number) in 10-digit and 13-digit formats. The output is always ISBN-13.
```py
from pydantic import BaseModel
from pydantic_extra_types.isbn import ISBN
class Book(BaseModel):
isbn: ISBN
book = Book(isbn="8537809667")
print(book)
```
output:
```py
#> isbn='9788537809662'
```
Selected Reviewer: @yezz123

Add: New type ISBN

---

pydantic_extra_types/payment.py
tests/test_types_payment.py

`str.isdigit` method actually allows non digit characters like `²` or `⑥`.
```python
>>> from pydantic_extra_types.payment import PaymentCardNumber
>>> PaymentCardNumber("²")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/rcaillon/.local/lib/python3.10/site-packages/pydantic_extra_types/payment.py", line 47, in __init__
card_number = self.validate_luhn_check_digit(card_number)
File "/home/rcaillon/.local/lib/python3.10/site-packages/pydantic_extra_types/payment.py", line 108, in validate_luhn_check_digit
sum_ = int(card_number[-1])
ValueError: invalid literal for int() with base 10: '²'
>>> PaymentCardNumber("⑥")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/rcaillon/.local/lib/python3.10/site-packages/pydantic_extra_ …
```

fix validate_digits actually allowing non digit characters

---

pydantic_extra_types/payment.py
tests/test_types_payment.py

♻️ refactor the `validate_brand` method & add new types

---

pydantic_extra_types/isbn.py

```
WARNING -  griffe: /Users/programming/pydantic_work/pydantic-extra-types/pydantic_extra_types/isbn.py:18: No type or
annotation for parameter 'value'
WARNING -  griffe: /Users/programming/pydantic_work/pydantic-extra-types/pydantic_extra_types/isbn.py:18: Parameter 'value'
does not appear in the function signature
WARNING -  griffe: /Users/programming/pydantic_work/pydantic-extra-types/pydantic_extra_types/isbn.py:37: No type or
annotation for parameter 'value'
WARNING -  griffe: /Users/programming/pydantic_work/pydantic-extra-types/pydantic_extra_types/isbn.py:37: Parameter 'value'
does not appear in the function signature
```

Fix refs blocking docs build

---

pyproject.toml

Allow python-ulid 2.x on Python 3.9 and later

---

pydantic_extra_types/isbn.py
pydantic_extra_types/mac_address.py

I try it locally its working fine

:memo: Refactor Documentation for ISBN and MAC address modules

---

pydantic_extra_types/language_code.py
tests/test_json_schema.py
tests/test_language_codes.py

Add language code definitions and test

---

pydantic_extra_types/pendulum_dt.py
tests/test_pendulum_dt.py

changed pendulum_dt to accept datetime as well. verifed no data is lost

add native datetime to pendulum_dt.py

---

pydantic_extra_types/pendulum_dt.py
requirements/pyproject.txt
tests/test_pendulum_dt.py

* removed handler that vas coercing it to native datetime values
* added test to verify correct typing after parsing

Fix a Pendulum date time object to have correct typing

---

.gitignore
pydantic_extra_types/pendulum_dt.py
tests/test_pendulum_dt.py

Preserve timezone information when validating Pendulum DateTimes

---

pydantic_extra_types/color.py

The current code uses a `try-except` block to handle a potential `KeyError` when looking up a color value in the `COLORS_BY_VALUE` and `COLORS_BY_NAME` dictionary:
**Proposed Change:**
Refactor the code to use an `if-else` conditional check instead of a `try-except` block. This change improves code readability and leverages a more predictable conditional flow:
**Benefits:**
- Enhances code readability by removing the exception handling for a simple key lookup.
- Clearly separates the logic for handling the presence and absence of the key in the dictionary.
**Impact:**
This change is expected to maintain the existing functionality while improving code clarity.
Please let me know if there are any specific tests or cases you would like me to address in this refactoring.
Thank you!

Replace try-except block by if-else statement

---

pydantic_extra_types/phone_numbers.py
tests/test_phone_numbers.py

A number of improvements for the existing phone number type validator
Primarily this change adds logic for the existing variable `supported_regions` in the validator, this was currently preforming no function at all. If a user supplies a list of two digit phone number regions to the class the validator will now call `phonenumbers` to check if the parsed number is indeed within one of the regions supplied or else raise a `ValidationError`. If `supported_regions` is an empty list (As is now the default), a valid phone number from any region will be accepted.
Additionally, this change:
- Removes unused imports and unused Generator type definition
- Removes non functional `supported_formats` variable , these values can be looked up from the `phonenumbers` library if needed, no need to …

feature: Improve phone number validator

---

pydantic_extra_types/semver.py
pyproject.toml
tests/test_semantic_version.py

closes #205  (shedules removal for next magor version so we do not break api contract)
reasons for selecting semantic_version in favor of semver is missing usual 
```python
try:
<import library that does this>
except:
raise RuntimeError(<here is how you install it>)
````
TLDR: it requres much more effort
however i folded test  from semver to semantic_version and extrended it so it can be just removed on deprecation

✨ deprecate `semver` in favor of `semantic_version`

---

pydantic_extra_types/s3.py
tests/test_json_schema.py
tests/test_s3.py

Not 100% if this was already made somewhere. 
Very simple s3 path parser but can still come in handy! 
Please let me know your thoughts. Feedback is always welcomed 🤗

feat: add S3Path

---

pyproject.toml

The API change in this major release is that a `TypeError` is raised instead of a `ValueError` if a constructor is called with the wrong type. I don’t *think* this requires any code changes in `pydantic-extra-types`, but it’s worth double-checking.
https://github.com/mdomke/python-ulid/releases/tag/3.0.0
Tested with:
```
$ python3.12 -m venv _e
$ . _e/bin/activate
(_e) $ pip install -e .[all]
(_e) $ pip install -r requirements/testing.in
(_e) $ python -m pytest
```

Allow python-ulid 3.0

---

pyproject.toml

This is a followup of 927dcd1069545bb9d2e06012f79a4a87a0c398a7.

Allow build with python-ulid 3.0.0

---

.pre-commit-config.yaml

🔨 added automatic syntax-upgrade hook ~ pyupgrade

---

pydantic_extra_types/currency_code.py
tests/test_currency_code.py

My shell added the dot to the url and brought me to a non existing wikipedia page. Adding a space after the url prevents that from happening

isolate url in Currency

---

pydantic_extra_types/currency_code.py
tests/test_currency_code.py

I think "eur" should be accepted as a currency and stored as "EUR" just like basically any date in a string is accepted as (and converted to) a datetime object

lower case currency is valid

---

.github/workflows/ci.yml
pydantic_extra_types/color.py
pydantic_extra_types/coordinate.py
pydantic_extra_types/domain.py
pydantic_extra_types/pendulum_dt.py
pydantic_extra_types/phone_numbers.py
pydantic_extra_types/routing_number.py
pydantic_extra_types/semver.py
pydantic_extra_types/timezone_name.py
pyproject.toml
tests/test_json_schema.py
tests/test_phone_numbers_validator.py
uv.lock

Fixes https://github.com/pydantic/pydantic-extra-types/issues/248

Add back Python 3.8 support

---

pydantic_extra_types/pendulum_dt.py
tests/test_pendulum_dt.py

When using the `Duration` type on a model it was losing the `month` information.  This is important because months have variable number of days; if you want a duration of "1 month" that's what you want; not 30 days.
This fixes https://github.com/pydantic/pydantic-extra-types/issues/242

Preserve months when using the Pendulum Duration type

---

pydantic_extra_types/isbn.py
tests/test_isbn.py

The code calculating checkdigit for ISBN10 runs a loop for numbers between 1 and 10 included. There are two issues:
1. it ignores the possibility of getting the checkdigit of `0` and then raises an `UnboundLocalError` because the variable `valid_check_digit` is never set
2. it actually does not have to run a loop to calculate this variable, therefore a minor performance optimization is possible
This PR includes an added test with a valid ISBN10 ending with a `0` that failed earlier but passes now.

Fix checkdigit calculation for ISBN10

---

pydantic_extra_types/isbn.py
pydantic_extra_types/routing_number.py

This PR just improved the readability of cyclic checksum calculations using `itertools.cycle` for repetitive factors.

Make checksum calculation more descriptive

---

pydantic_extra_types/mac_address.py

Rewrite the `validate_mac_address` method to validate and convert the mac address more descriptively. The `bytearray` has been replaced by a string and a list of integers. No change of functionality.

Refactor validate_mac_address method

---

pydantic_extra_types/pendulum_dt.py
tests/test_pendulum_dt.py

Follow up to #296 which fixes/improves (de-)serialization of `Duration` models.
This PR:
- limits iso8601 serialization to json
- adds json serialization to test case
- checks for equality of years and months explicitly

limit iso8601 serialization of duration to json

---

pydantic_extra_types/mongo_object_id.py

Fixes #300.
Serialization on model_dump = ObjectId
Serialization on model_dump_json = str

Fix serialization of mongo_object_id

---

pydantic_extra_types/timezone_name.py

The zoneinfo module by default uses the systems timezone information and if not found falls back to tzdata. This change makes `get_timezone()` behave the same allowing for tzdata to fully become an optional dependency for Linux distributions which already include time zone data.
Closes: #291

Default to using system zoneinfo if available

---

pydantic_extra_types/ulid.py
tests/test_ulid.py

Since True/False in python pass isinstance(value,int) with I would be reasonable according to principle of least astonishment to additionaly check and discriminate against bool values in ULID validator.

fix: disallow bool as input value for ULID

---

pydantic_extra_types/domain.py
tests/test_domain.py

AS discussed in 307, issues with domain regexp allowed ip address and cidr
* updated regexp
* added tests for ip and cidr
* moved pattern to be a class var that can be overridden on deman

♻️ Fix regex pattern for Domain

---

pydantic_extra_types/color.py
tests/test_types_color.py

Fixes: https://github.com/pydantic/pydantic-extra-types/issues/311

Fix color parsing when TypeError

---

pydantic_extra_types/path.py
tests/test_path.py

This pull request adds new types for paths that extend the base types by converting relative paths to absolute ones.
fixes #149

Add path types

---

pydantic_extra_types/coordinate.py
tests/test_coordinate.py
tests/test_json_schema.py

It implements the request from https://github.com/pydantic/pydantic-extra-types/issues/284

feat: Support `Decimal` type in coordinates

---

pydantic_extra_types/ulid.py
tests/test_json_schema.py
tests/test_ulid.py

Allow constructing an ULID from an `uuid.UUID`

---

pydantic_extra_types/payment.py
tests/test_types_payment.py

This pull request adds support for the Diners Club payment card brand and adds extends Mastercard brand validation
https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_(IIN)

feat: update credit card brands

---

pydantic_extra_types/domain.py
tests/test_domain.py

1. Added parameterized tests for valid/invalid domain strings
2. Included tests for punycode domains and non-string input types
3. Ensured edge cases like trailing dots, missing TLDs, and long domains are covered

Added test coverage for DomainStr validation including punycode and invalid inputs

---

tests/test_path.py

Fix #332
---
Add drive compatibility check before using os.path.relpath():
- If different drives on Windows → return absolute path
- Otherwise → return relative path as before

Fix relative path creation on Windows for fixtures

---

pydantic_extra_types/phone_numbers.py

I've noticed that this method is not up to convention, as it should be decorated with `@classmethod`.

🐛 set `@classmethod` in `phone_numbers` schema

---

pydantic_extra_types/phone_numbers.py

This will close https://github.com/pydantic/pydantic-extra-types/issues/107
Improve the documentation for the PhoneNumber class by adding detailed usage examples, demonstrating normal usage, subclassing for default changes, and using the provided validator annotation.

📝 docs: enhance docstring for `PhoneNumber` class with usage examples

---

pydantic_extra_types/cron.py
pyproject.toml
tests/test_cron.py
tests/test_json_schema.py
uv.lock

Added cron type
